### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nigelhorne** [speculatrix/zabbix-flexlm#3]
Please add support for FlexLM running on a Windows server

**Comment by speculatrix** [comment]
This repository is for a plugin for zabbix monitoring. This is not a support site run by the owners of FlexLM

**Comment by speculatrix** [comment]
Hi, I misunderstood the request, sorry.
The zabbix plugin runs on the machine running the licence server. I would guess you'd need to rewrite it in python to make it run on windows. I'm afraid I don't have access to a suitable box to do this.
I'm happy to accept submissions.
