### ISSUE TITLE
Instructions for Template Import

### ISSUE THREAD

**Issue by hullio1979** [speculatrix/zabbix-flexlm#5]
I am using Zabbix 4.0. What instructions should I use to import the template on the server? Is this through the web interface? I tried there but got an error for invalid metadata. Thanks.

**Comment by speculatrix** [comment]
yes, you import the XML using the web interface as admin.
I no longer have access to a FlexLM server to play with the tooling. It should be possible to edit the template XML and fix the problems you see when trying to import it, sorry, I can't really help you too much.

**Comment by hullio1979** [comment]
Thanks for the quick response. I found the issue. For each of my flexlm services I assume I have to create a new template file and change the names to match? For example I have Xilinx, Mentor, and Intel tools. I need 3 template files, 3 scripts, and 3 configs correct?

                Jon

**Comment by speculatrix** [comment]
I did have a play with a version that would work with multiple licences.dat file but I think it wasn't great.

so I would set up multiple plugins so that you have different names to access the licence files, and then call the script (or copy the script) so that it works with the difference licence dat files.

sorry if this is vague.

**Comment by hullio1979** [comment]
No this makes sense. Thanks. Still have issues with the template. Will probably have to create the server side feature manually.

**Comment by hullio1979** [comment]
Quick question, the import did not work but I was able to configure the template through the web server. Under discovery rules I created the item prototypes, trigger prototypes, and graph prototypes. What I am not finding is how do I add the graph to my dashboard? Thanks.

**Comment by hullio1979** [comment]
I was able to get everything to work by recreating the server settings through the web server. Thanks for the help.

**Comment by speculatrix** [comment]
Glad you worked it out.
